language: ruby

sudo: false

env:
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=luajit

addons:
  apt:
    packages:
      - $LUA

script:
  - $LUA deferred_test.lua

notifications:
  email:
    on_success: change
    on_failure: always
