language: ruby

sudo: false

env:
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=luajit

before_install:
  - sudo apt-get install $LUA -qq

script:
  - $LUA deferred_test.lua

notifications:
  email:
    on_success: change
    on_failure: always
